# Generated by Django 5.2 on 2025-04-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='img',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
