# Generated by Django 5.2 on 2025-05-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderid',
            field=models.IntegerField(),
        ),
    ]
